Repository oasis-tcs/odata-specs, pull requests merged in 2023-08, with the labels that each got.

#82 Examples in 11 Data Service Requests.md
  docs/odata-csdl-json/odata-csdl-json.pdf
  docs/odata-csdl-xml/odata-csdl-xml.pdf
  docs/odata-data-aggregation-ext/odata-data-aggregation-ext.pdf
  docs/odata-json-format/odata-json-format.pdf
  docs/odata-protocol/odata-protocol.html
  docs/odata-protocol/odata-protocol.md
  docs/odata-protocol/odata-protocol.pdf
  docs/odata-url-conventions/odata-url-conventions.pdf
  odata-protocol/11 Data Service Requests.md
Labels: Core

#98 Simplify and align workflow scripts
  .github/workflows/nodejs.yml
  .github/workflows/pdf.yml
  package.json
Labels: tools

#97 Automated HTML abstracts
  docs/odata-csdl-json/odata-csdl-json.html
  docs/odata-csdl-json/odata-csdl-json.pdf
  docs/odata-csdl-xml/odata-csdl-xml.html
  docs/odata-csdl-xml/odata-csdl-xml.md
  docs/odata-csdl-xml/odata-csdl-xml.pdf
  docs/odata-data-aggregation-ext/odata-data-aggregation-ext.html
  docs/odata-data-aggregation-ext/odata-data-aggregation-ext.pdf
  docs/odata-json-format/odata-json-format.html
  docs/odata-json-format/odata-json-format.pdf
  docs/odata-protocol/odata-protocol.html
  docs/odata-protocol/odata-protocol.pdf
  docs/odata-url-conventions/odata-url-conventions.html
  docs/odata-url-conventions/odata-url-conventions.pdf
  odata-csdl/0 frontmatter.md
  odata-csdl/json.yaml
  odata-csdl/xml.yaml
  odata-data-aggregation-ext/0 frontmatter.md
  odata-data-aggregation-ext/meta.yaml
  odata-json-format/0 frontmatter.md
  odata-json-format/meta.yaml
  odata-protocol/0 frontmatter.md
  odata-protocol/meta.yaml
  odata-url-conventions/0 frontmatter.md
  odata-url-conventions/meta.yaml
  package-lock.json
  package.json
Labels: tools

#110 Cleanup odata-url-conventions
  odata-url-conventions/temp/odata-v4.01-os-part2-url-conventions-clean.html
  odata-url-conventions/temp/odata-v4.01-os-part2-url-conventions-raw.md
  odata-url-conventions/temp/odata-v4.01-os-part2-url-conventions.html
  odata-url-conventions/temp/odata-v4.01-os-part2-url-conventions.md
Labels: Core

#163 Sort spec list on index page by name
  docs/index.md
  lib/build.js
Labels: tools

#96 Non-material changes to OData-Data-Aggr-Ext V4.0 CSD04
  docs/odata-data-aggregation-ext/odata-data-aggregation-ext.html
  docs/odata-data-aggregation-ext/odata-data-aggregation-ext.md
  odata-data-aggregation-ext/3.2 Basic Aggregation.md
  odata-data-aggregation-ext/3.4 Transformations Changing the Input Set Structure.md
  odata-data-aggregation-ext/3.6 Expressions Evaluable on a Collection.md
  odata-data-aggregation-ext/7 Examples.md
Labels: Aggregation

#75 Example sale 8 is for product P3, not P1
  docs/odata-data-aggregation-ext/odata-data-aggregation-ext.html
  docs/odata-data-aggregation-ext/odata-data-aggregation-ext.md
  odata-data-aggregation-ext/1 Introduction.md
Labels: Aggregation
